<?php

return [
  'brandAliases' => [
    'yahama' => 'yamaha',
  ],
  'brands' => [
    'bosch' => 'Bosch',
    'yamaha' => 'Yamaha',
    'shimano' => 'Shimano',
    'bafang' => 'Bafang',
    'brose' => 'Brose',
    'generic' => 'Generic',
  ],
  'errorCatalog' => [
    'bosch' => [
      '410' => [
        'title' => 'Internal Drive Unit Error',
        'severity' => 'High',
        'description' => 'Drive unit reported an internal fault and disabled power assist for component protection.',
        'what' => 'The motor controller found unstable internal communication.',
        'causes' => ['Firmware issue', 'Motor controller fault', 'Overheating'],
        'symptoms' => ['No motor assist', 'Intermittent cut-out', 'Error shown on display'],
        'fix' => ['Power cycle bike', 'Check firmware at dealer', 'Run electrical inspection'],
        'rideability' => 'Caution',
        'urgency' => 'Soon',
      ],
      '414' => [
        'title' => 'Motor Voltage Error',
        'severity' => 'High',
        'description' => 'Abnormal voltage in motor circuit. Riding can worsen controller damage.',
        'what' => 'Voltage flow is outside expected safety range.',
        'causes' => ['Loose battery connection', 'Battery cell imbalance', 'Controller fault'],
        'symptoms' => ['Power drop', 'No assist', 'Sudden shutdown'],
        'fix' => ['Reseat battery', 'Clean contacts', 'Test battery health', 'Visit service center'],
        'rideability' => 'Stop',
        'urgency' => 'Immediate',
      ],
    ],
    'yamaha' => [
      'e01' => [
        'title' => 'Motor Communication Fault',
        'severity' => 'High',
        'description' => 'Motor and display/control unit lost communication.',
        'what' => 'Critical data exchange between controller and drive unit failed.',
        'causes' => ['Harness connector issue', 'Water ingress', 'Controller board fault'],
        'symptoms' => ['Assist disabled', 'Error at startup', 'Unstable assist'],
        'fix' => ['Power cycle', 'Inspect connectors', 'Dry and clean contacts', 'Dealer diagnostics'],
        'rideability' => 'Caution',
        'urgency' => 'Soon',
      ],
      'w001' => [
        'title' => 'Motor Internal Sensor Error',
        'severity' => 'High',
        'description' => 'Internal motor sensor feedback is invalid.',
        'what' => 'Drive system cannot measure motor state accurately.',
        'causes' => ['Sensor drift', 'Motor board issue'],
        'symptoms' => ['Weak assist', 'Delayed boost', 'Unexpected cutoff'],
        'fix' => ['Restart system', 'Check firmware', 'Service calibration'],
        'rideability' => 'Caution',
        'urgency' => 'Soon',
      ],
    ],
    'shimano' => [
      'w013' => [
        'title' => 'Torque Sensor Initialization',
        'severity' => 'Medium',
        'description' => 'Torque sensor failed to initialize correctly at power-on.',
        'what' => 'Assist calibration did not complete with stable pedal force reference.',
        'causes' => ['Pedal pressure during startup', 'Sensor calibration drift'],
        'symptoms' => ['Weak assist', 'Delayed assist engagement'],
        'fix' => ['Power on without pedal load', 'Restart system', 'Run service calibration'],
        'rideability' => 'Caution',
        'urgency' => 'Soon',
      ],
    ],
    'bafang' => [
      '21' => [
        'title' => 'Speed Sensor Error',
        'severity' => 'Medium',
        'description' => 'Speed signal is missing or implausible.',
        'what' => 'Controller cannot read wheel speed correctly.',
        'causes' => ['Magnet misalignment', 'Sensor cable damage'],
        'symptoms' => ['Wrong speed reading', 'Assist limit issues'],
        'fix' => ['Realign magnet', 'Check sensor cable', 'Replace damaged sensor'],
        'rideability' => 'Caution',
        'urgency' => 'Soon',
      ],
    ],
    'brose' => [
      '504' => [
        'title' => 'Temperature Derating',
        'severity' => 'Medium',
        'description' => 'Motor is hot; controller reduced output to protect system.',
        'what' => 'Thermal safeguard mode activated.',
        'causes' => ['Long climb under load', 'High ambient heat'],
        'symptoms' => ['Reduced acceleration', 'Limited assist'],
        'fix' => ['Cool bike', 'Reduce assist level', 'Inspect airflow and load'],
        'rideability' => 'Caution',
        'urgency' => 'Info',
      ],
    ],
    'generic' => [
      'e01' => [
        'title' => 'Throttle Fault',
        'severity' => 'Medium',
        'description' => 'Throttle signal out of expected range.',
        'what' => 'Controller receives unstable throttle voltage.',
        'causes' => ['Loose connector', 'Sensor failure', 'Moisture in harness'],
        'symptoms' => ['No throttle', 'Sudden cut', 'Startup warning'],
        'fix' => ['Reconnect throttle plug', 'Dry connectors', 'Test replacement throttle'],
        'rideability' => 'Caution',
        'urgency' => 'Soon',
      ],
      'e07' => [
        'title' => 'Motor Hall Sensor Fault',
        'severity' => 'High',
        'description' => 'Hall feedback missing; commutation may fail.',
        'what' => 'Controller cannot synchronize phase timing safely.',
        'causes' => ['Hall wire damage', 'Controller fault', 'Motor sensor failure'],
        'symptoms' => ['Judder', 'No start', 'Heat buildup'],
        'fix' => ['Inspect hall wiring', 'Check motor cable', 'Replace failed sensor'],
        'rideability' => 'Stop',
        'urgency' => 'Immediate',
      ],
    ],
  ],
  'settingsCatalog' => [
    'generic' => [
      'p01' => [
        'title' => 'Display Brightness',
        'summary' => 'Adjust screen backlight level.',
        'details' => 'Higher brightness improves outdoor readability but can slightly increase consumption.',
        'values' => ['1 = low', '2 = medium', '3 = high'],
        'notes' => ['Increase for sunlight use'],
      ],
      'p06' => [
        'title' => 'Wheel Size',
        'summary' => 'Sets wheel diameter used for speed and distance calculations.',
        'details' => 'Incorrect value will distort speedometer and trip calculations.',
        'values' => ['Set actual wheel size in inches'],
        'notes' => ['Common values: 20, 24, 26, 27.5, 29'],
      ],
      'p08' => [
        'title' => 'Speed Limit',
        'summary' => 'Maximum assisted speed threshold.',
        'details' => 'Controller behavior depends on firmware and legal region limits.',
        'values' => ['Set to local legal requirement'],
        'notes' => ['Always follow local regulations'],
      ],
    ],
    'bosch' => [
      'assist-mode' => [
        'title' => 'Assist Profile',
        'summary' => 'Tune Eco, Tour, Sport, Turbo response.',
        'details' => 'Adjusts support percentage and responsiveness to pedal force.',
        'values' => ['Eco = max range', 'Turbo = max support'],
        'notes' => ['Use official Bosch tools where available'],
      ],
    ],
    'shimano' => [
      'assist-character' => [
        'title' => 'Assist Character',
        'summary' => 'Natural versus aggressive support behavior.',
        'details' => 'Changes startup and sustained torque feel.',
        'values' => ['Comfort', 'Sport', 'Custom'],
        'notes' => ['Configure via compatible Shimano tools'],
      ],
    ],
    'yamaha' => [
      'power-curve' => [
        'title' => 'Power Curve',
        'summary' => 'Tune efficiency versus climbing response.',
        'details' => 'Higher response gives stronger assist but can drain battery faster.',
        'values' => ['Economy', 'Standard', 'High'],
        'notes' => ['Match mode to terrain and range goals'],
      ],
    ],
    'bafang' => [
      'current-limit' => [
        'title' => 'Controller Current Limit',
        'summary' => 'Caps peak electrical current.',
        'details' => 'Higher values increase acceleration and thermal load.',
        'values' => ['Set below battery and controller max rating'],
        'notes' => ['Avoid over-limit settings to prevent damage'],
      ],
    ],
    'brose' => [
      'support-level' => [
        'title' => 'Support Level',
        'summary' => 'Overall motor support intensity.',
        'details' => 'Balances smoothness, battery range, and punch.',
        'values' => ['Low', 'Medium', 'High'],
        'notes' => ['Use conservative levels for range'],
      ],
    ],
  ],
];
