<?php

$fullGenericSettings = ['p01','p02','p03','p04','p05','p06','p07','p08','p09','p10','p11','p12','p13','p14','p15','p16'];
$fullGenericErrors = ['e01','e02','e03','e05','e06','e07','e08','e09','e10','e11','e21','e22','e24','e25','e30'];

return [
  'sw900' => [
    'name' => 'SW900',
    'family' => 'Generic Chinese LCD Display',
    'summary' => 'Common LCD display used on many Chinese controllers, conversion kits and delivery e-bikes.',
    'keywords' => ['SW900 P settings', 'SW900 error codes', 'SW900 speed limit', 'SW900 voltage setting'],
    'settings' => $fullGenericSettings,
    'errors' => $fullGenericErrors,
    'notes' => ['Most SW900 menus depend on controller firmware.', 'P08 and P14 affect speed and current, so adjust carefully.', 'Always match P03 voltage and P06 wheel size to the actual bike.'],
  ],
  'gd01' => [
    'name' => 'GD01',
    'family' => 'Generic Display Family',
    'summary' => 'Common generic display family used with many hub-motor controller kits.',
    'keywords' => ['GD01 error codes', 'GD01 display settings', 'GD01 ebike display'],
    'settings' => ['p01','p02','p03','p04','p06','p08','p09','p10','p11','p12','p14','p15'],
    'errors' => ['e01','e02','e03','e05','e06','e07','e08','e09','e21','e22','e30'],
    'notes' => ['GD01 labels can vary between sellers.', 'If the code is unclear, compare symptoms with the generic controller guide.'],
  ],
  'gd02' => [
    'name' => 'GD02',
    'family' => 'Generic Display Family',
    'summary' => 'Common generic display family similar to GD01, often bundled with budget hub-motor kits.',
    'keywords' => ['GD02 error codes', 'GD02 display settings', 'GD02 controller fault'],
    'settings' => ['p01','p02','p03','p04','p06','p08','p09','p10','p11','p12','p14','p15'],
    'errors' => ['e01','e02','e03','e05','e06','e07','e08','e09','e21','e22','e30'],
    'notes' => ['GD02 menus may use seller-specific wording.', 'Check controller voltage before changing P03 or low-voltage settings.'],
  ],
  's866' => [
    'name' => 'S866',
    'family' => 'Generic Chinese LCD Display',
    'summary' => 'Common LCD display often found with 36V and 48V hub-motor e-bike systems.',
    'keywords' => ['S866 P settings', 'S866 error codes', 'S866 P08', 'S866 P14'],
    'settings' => $fullGenericSettings,
    'errors' => $fullGenericErrors,
    'notes' => ['S866 parameter labels can vary by seller.', 'Wrong P03 voltage can make the battery indicator inaccurate.', 'Wrong P06 wheel size causes wrong speed readings.'],
  ],
  's830' => [
    'name' => 'S830',
    'family' => 'Compact Generic Display',
    'summary' => 'Compact display often bundled with hub-motor kits and basic controller systems.',
    'keywords' => ['S830 error codes', 'S830 settings', 'S830 ebike display'],
    'settings' => ['p01','p02','p03','p04','p06','p08','p09','p10','p11','p12','p14','p15'],
    'errors' => ['e01','e02','e03','e05','e06','e07','e21','e22','e30'],
    'notes' => ['S830 is usually simpler than SW900/S866.', 'Start with wheel size, voltage and speed limit if readings look wrong.'],
  ],
  'kt-lcd3' => [
    'name' => 'KT LCD3',
    'family' => 'Kunteng / KT Controller Display',
    'summary' => 'KT controller and LCD3-style display system with deeper controller parameter options.',
    'keywords' => ['KT LCD3 settings', 'KT controller P settings', 'KT LCD3 error codes'],
    'settings' => ['p01','p02','p03','p04','p05','p06','p07','p08','p09','p10','p11','p12','p13','p14','p15'],
    'errors' => ['e03','e05','e06','e07','e08','e09','e21','e22','e30'],
    'notes' => ['KT displays may use both P and C parameter groups.', 'Current and PAS settings should match controller and battery ratings.'],
  ],
  'ukc1' => [
    'name' => 'UKC1 / UKC-1',
    'family' => 'Basic Generic LCD Display',
    'summary' => 'Very common basic LCD display used with many conversion kits and generic controllers.',
    'keywords' => ['UKC1 error codes', 'UKC1 settings', 'UKC-1 display error'],
    'settings' => ['p01','p02','p03','p04','p06','p08','p09','p10','p11','p12','p14','p15'],
    'errors' => ['e01','e02','e03','e05','e06','e07','e08','e21','e22','e30'],
    'notes' => ['UKC1 variants can look similar but use different controller firmware.', 'If a setting is missing on your display, it may be locked by firmware.'],
  ],
  'm5' => [
    'name' => 'M5',
    'family' => 'Generic Compact Display',
    'summary' => 'Widely used display family including M5 and similar variants.',
    'keywords' => ['M5 display error codes', 'M5 display settings', 'generic ebike display errors'],
    'settings' => ['p01','p03','p06','p08','p10','p11','p12','p14','p15'],
    'errors' => ['e01','e02','e06','e07','e08','e21','e22','e30'],
    'notes' => ['If the display shows E07 or E30, check motor/controller wiring first.', 'Settings are controller-dependent.'],
  ],
  'other' => [
    'name' => 'Other / Not sure',
    'family' => 'Generic Chinese E-Bike System',
    'summary' => 'Use this option when you are not sure which display or controller model you have.',
    'keywords' => ['generic ebike error codes', 'unknown ebike display error', 'Chinese ebike controller settings'],
    'settings' => $fullGenericSettings,
    'errors' => $fullGenericErrors,
    'notes' => ['If your model is not listed, compare the visible code and symptoms.', 'Take a clear photo of the label or display and use Scan where possible.'],
  ],
];
